version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  data-producer:
    image: mobimeo/test-data-clients:0.1
    container_name: test-data-producer
    depends_on:
      - broker
    environment:
      BOOTSTRAP_SERVERS: 'PLAINTEXT://broker:29092'
      TOPIC: 'delays'
      MODE: 'producer'
      CLIENT_ID: 'test-producer'
      MAX_PUBLISH_INTERVAL_SECONDS: '10'

  data-consumer:
    image: mobimeo/test-data-clients:0.1
    container_name: test-data-consumer
    depends_on:
      - broker
      - data-producer
    environment:
      BOOTSTRAP_SERVERS: 'PLAINTEXT://broker:29092'
      TOPIC: 'delays'
      MODE: 'consumer'
      CLIENT_ID: 'test-consumer'
      CONSUMER_GROUP: 'test-consumer-group'
